services:

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - lake

  mc-init:
    image: 'minio/mc'
    container_name: mc-init
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add dmlminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet dmlminio/raw;
      /usr/bin/mc admin service restart dmlminio;
      "
    depends_on:
      - minio
    networks:
      - lake

networks:
  lake:
